site_name: R-type C++
site_description: >-
  The R-type C++ project is a 2D game based on the R-type game. R-type comes
  with a custom game engine usable as a library.

nav:
  - Home:
      - "Welcome": index.md
      - "User Guide": "user-guide.md"
      - "Contribute": "contribute.md"
  - "Engine":
      - "Core" : "engine/core.md"
      - "SparseArray" : "engine/sparseArray.md"
      - "Addons":
          - "Acceleration": "engine/addons/acceleration.md"
          - "Collider": "engine/addons/collider.md"
          - "Limits": "engine/addons/limits.md"
          - "Velocity": "engine/addons/velocity.md"
      - "Components" :
          - "Hitbox": "engine/addons/hitbox.md"
          - "Transform": "engine/addons/transform.md"
  - "Client":
      - "main": "client/main.md"
      - "Renderer": "client/renderer.md"
      - "SetMousePosition": "client/setMousePosition.md"
      - "NetWorker": "client/netWorker.md"
      - "Renderer": "client/renderer.md"
      - "SoundRenderer": "client/soundRenderer.md"
      - "TextRenderer": "client/textRenderer.md"
      - "Scene":
        - "Game": "client/scene/gameScene.md"
        - "Menu": "client/scene/menuScene.md"
        - "Lobby": "client/scene/lobbyScene.md"
      - "Addons":
          - "IsClicked": "client/addons/IsClicked.md"
          - "IsHover": "client/addons/IsHover.md"
          - "OnHoverSprite": "client/addons/OnHoverSprite.md"
          - "CollisionWaveSpawn" : "client/addons/CollisionWaveSpawn.md"
          - "EnemyInfiniteSpawn" : "client/addons/EnemyInfiniteSpawn.md"
          - "EnemyWaveSpawn": "client/addons/EnemyWaveSpawn.md"
          - "ShipAnimation": "client/addons/ShipAnimation.md"
          - "Parallax": "client/addons/Parallax.md"
          - "SpriteAnimation" : "client/addons/SpriteAnimation.md"
      - "Components" :
          - "MousePosition" : "client/components/MousePosition.md"
          - "NumberLevels" : "client/components/NumberLevels.md"
          - "NumberPlayers" : "client/components/NumberPlayers.md"
          - "RendererTexture" : "client/components/RendererTexture.md"
          - "SendPacket" : "client/components/SendPacket.md"
          - "SoundComponent" : "client/components/SoundComponent.md"
      - "Systems":
          - "CheckDamage": "client/systems/CheckDamage.md"
          - "CheckHealth": "client/systems/CheckHealth.md"
          - "CheckInvulnerability": "client/systems/CheckInvulnerability.md"
          - "CheckSolidCollider": "client/systems/CheckSolidCollider.md"

  - "Server":
      - "Getting Started": "server/index.md"
      - "Protocol":
          - "RFC": "server/rfc.md"

    #   - "Software":
    #       - "Architecture": "server/architecture.md"
  #- "Library":
      #- "Getting Started": "library/index.md"
      #- "Life Cycle": "library/life_cycle.md"
      #- "Concepts":
          #- "Entity": "library/entity.md"
          #- "Component": "library/component.md"
          #- "System": "library/system.md"
          #- "Scenes": "library/scenes.md"
          #- "Game Loop": "library/game_loop.md"
  - "About":
      - "Release Notes": "about/index.md"
      - "License": "about/license.md"

theme:
  name: material
  features:
    # - announce.dismiss
    # - content.action.edit
    # - content.action.view
    # - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.tabs.link
    # - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.footer
    # - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    # - search.share
    # - search.suggest
    # - toc.follow
    # - toc.integrate

markdown_extensions:
  - tables